# ALERT SEVERITY

LOW = "LOW"
MEDIUM = "MEDIUM"
HIGH = "HIGH"
CRITICAL = "CRITICAL"

# INCIDENT STATUS

OPEN = "OPEN"
INVESTIGATING = "INVESTIGATING"
CLOSED = "CLOSED"

# ALERT STATUS

ACTIVE = "ACTIVE"
RESOLVED = "RESOLVED"

# DETECTION TYPES

BRUTE_FORCE = "SSH Brute Force"
NETWORK_SCAN = "Network Scan"
REVERSE_SHELL = "Reverse Shell"

# MITRE TACTICS

RECON = "Reconnaissance"
CREDENTIAL_ACCESS = "Credential Access"
EXECUTION = "Execution"